### ISSUE TITLE
A Question

### ISSUE THREAD

**Issue by XdpAreKid** [yhenon/pytorch-retinanet#10]
[At here](https://github.com/yhenon/pytorch-retinanet/blob/6db46e59061bd73fd44900bd8e932df18ba83723/csv_eval.py#L89),why use '.permute(2, 0, 1)',but [in here](https://github.com/yhenon/pytorch-retinanet/blob/6db46e59061bd73fd44900bd8e932df18ba83723/train.py#L129), do not use it.

**Comment by yhenon** [comment]
Thanks for pointing this out, I believe it may be a bug. I'm looking into it now.

**Comment by yhenon** [comment]
This is not a bug.
Basically images are loaded and then batched when training (2nd linked example). During batching, the permutation is done.

In the testing code (1st linked example), no batching is performed, so the permutation has to be added manually.

The code for permuting in the batching is here:  https://github.com/yhenon/pytorch-retinanet/blob/master/dataloader.py#L336
