### ISSUE TITLE
Subtraction, the `-` operator, with a bool tensor is not supported

### ISSUE THREAD

**Issue by k--chow** [yhenon/pytorch-retinanet#106]
Subtraction, the `-` operator, with a bool tensor is not supported. If you are trying to invert a mask, use the `~` or `bitwise_not()` operator instead. What and where is this error coming from when training?

**Comment by overflo94** [comment]
Are you using Pytroch 1.2? You might want to downgrade to 1.1.0 to avoid this error, this resolved it for me. 

Additional info:
https://github.com/OpenNMT/OpenNMT-py/issues/1525
https://github.com/OpenNMT/OpenNMT-py/issues/1524

**Comment by k--chow** [comment]
This worked. Thank you.

**Comment by ouening** [comment]
pytorch:1.2.0
CUDA:10.0
Is there any other way to  solve it? I don't want to downgrade pytorch.
