### ISSUE TITLE
How to test one image?

### ISSUE THREAD

**Issue by Summar-sky** [yhenon/pytorch-retinanet#118]
Excuse me, who can help me?  how do you test one image?

**Comment by MadsDyrmann** [comment]
I've modified visualize.py to work on single images:
[eval_singleImage.py](https://github.com/MadsDyrmann/pytorch-retinanet/blob/master/eval_singleImage.py)

**Comment by DecentMakeover** [comment]
@Summar-sky  if this fixes your problem, please close the issue.

**Comment by daveboat** [comment]
@MadsDyrmann I believe you are missing a normalization step after you load your images, in your evaluation code, after line https://github.com/MadsDyrmann/pytorch-retinanet/blob/93784f649388ee760c9f86f0d65fe2d978d08428/eval_singleImage.py#L81

**Comment by daveboat** [comment]
> @MadsDyrmann I believe you are missing a normalization step after you load your images, in your evaluation code, after line https://github.com/MadsDyrmann/pytorch-retinanet/blob/93784f649388ee760c9f86f0d65fe2d978d08428/eval_singleImage.py#L81

To be precise, you need something like
`im = im.astype(np.float32) / 255.0`
