### ISSUE TITLE
adding another classification head

### ISSUE THREAD

**Issue by DecentMakeover** [yhenon/pytorch-retinanet#119]
How could i add another classification head? So that i get two classification scores for every box and one regression score.

Thanks.

**Comment by yhenon** [comment]
Sure you can definitely do that if you modify the code. What are you trying to achieve?

**Comment by DecentMakeover** [comment]
Along with the classification score of the box and the box regression for the box.I want to classify one more score, specifically it is an erosion score specific to my dataset.

Could you tell me what files would i need to modify?

Thanks in advance.
