### ISSUE TITLE
Adding augmentation from albumentation

### ISSUE THREAD

**Issue by DecentMakeover** [yhenon/pytorch-retinanet#121]
Hello 

@yhenon 

I wanted to add more augmentation and was considering adding augmentations from albumentation library.But can this be added without any severe modifications because i was looking at this function 

    class Resizer(object):
        """Convert ndarrays in sample to Tensors."""

        def __call__(self, sample, min_side=608, max_side=1024):
            image, annots = sample['img'], sample['annot']

            rows, cols, cns = image.shape

            smallest_side = min(rows, cols)

            # rescale the image so the smallest side is min_side
            scale = min_side / smallest_side

            # check if the largest side is now greater than max_side, which can happen
            # when images have a large aspect ratio
            largest_side = max(rows, cols)

            if largest_side * scale > max_side:
                scale = max_side / largest_side

            # resize the image with the computed scale
            image = skimage.transform.resize(image, (int(round(rows*scale)), int(round((cols*scale)))))
            rows, cols, cns = image.shape

            pad_w = 32 - rows%32
            pad_h = 32 - cols%32

            new_image = np.zeros((rows + pad_w, cols + pad_h, cns)).astype(np.float32)
            new_image[:rows, :cols, :] = image.astype(np.float32)

            annots[:, :4] *= scale

            return {'img': torch.from_numpy(new_image), 'annot': torch.from_numpy(annots), 'scale': scale}

so here the annotations are being rescaled.So would this be an issue in using albumentation out of the box?

Thanks in advance.

**Comment by yhenon** [comment]
it depends which transforms you use. Transforms that modify the image shape (such as zoom, rotate,...) need to have the bounding boxes modified alongside. Transforms that do not modify the image shape (like brightness, gaussian noise) can be safely applied with no changes to the bboxes :)
