### ISSUE TITLE
resize image

### ISSUE THREAD

**Issue by LIUHAO121** [yhenon/pytorch-retinanet#122]
in dataloader.py 365 row
pad_w = 32 - rows%32
pad_h = 32 - cols%32
new_image = np.zeros((rows + pad_w, cols + pad_h, cns)).astype(np.float32)
i do not understand the effect of this code after resize frame.

**Comment by yhenon** [comment]
our model requires the image size to be a multiple of 32 (because of the 5 pooling layers, `2^5 == 32`). So we pad the image with zeros

**Comment by LIUHAO121** [comment]
The backbone network has 5 pooling layers and the fpn network has 2 pooling layers, why does not consider the pooling layers of fpn?
