### ISSUE TITLE
KeyError while loading the pre-trained retinanet model.

### ISSUE THREAD

**Issue by MaddyThakker** [yhenon/pytorch-retinanet#124]
`import torchvision.models as model`
`retinanet = model.resnet50(num_classes=720,)`
`retinanet.load_state_dict(torch.load("/content/drive/MyDrive/coco_resnet_50_map_0_335_state_dict.pt"))`

This is the error - 

RuntimeError: Error(s) in loading state_dict for ResNet:
	Missing key(s) in state_dict: "fc.weight", "fc.bias". 
        Unexpected key(s) in state_dict: "fpn.P5_1.weight", "fpn.P5_1.bias",

**Comment by astekardis** [comment]
@MaddyThakker Were you able to solve this issue?

**Comment by MaddyThakker** [comment]
@astekardis yes, change the num_classes = 80
Because pretrained model was trained on 80 classes.

**Comment by suarezjessie** [comment]
Hi @MaddyThakker, where do I insert this code snippet specifically to make the training work? Thanks!
