### ISSUE TITLE
Class mapping for MS Coco Dataset

### ISSUE THREAD

**Issue by MaddyThakker** [yhenon/pytorch-retinanet#125]
Hi, 
Where can I find the class-mapping for the MS Coco dataset the pre-trained model was trained on?
I am looking for mappings of type - 
_classname, id_

**Comment by yhenon** [comment]
For MS Coco, the generator relies on the coco api (here: https://github.com/cocodataset/cocoapi/).
You can load the categories as such:  https://github.com/cocodataset/cocoapi/blob/master/PythonAPI/pycocoDemo.ipynb
