### ISSUE TITLE
Changing the values of batch size 

### ISSUE THREAD

**Issue by DecentMakeover** [yhenon/pytorch-retinanet#13]
Hi Yann!

I have 2 GPU's and currently its taking up about 4 G.B of GPU, but even if i increase the batch size , the code does not throw any error, but it does not take up more GPU space.Anything obvious im missing here!

Thanks

**Comment by yhenon** [comment]
Hi,

I'm not able to reproduce this issue. 

Keep in mind that pytorch does multi-GPU by dividing the elements of a batch across all the GPUs. So you need to increase the batch size in proportion to the number of GPUs to keep the same memory use as using 1 GPU.

If you still have the issue, please post the command you are entering along with the memory use reported y `nvidia-smi`.

**Comment by bkj** [comment]
@yhenon You report `map=33.7` in the docs -- what parameter settings was that model trained with?  If I increase the batch size, how might I expect the `map` to change?

**Comment by yhenon** [comment]
@bkj the model was trained with the parameters in the repo as is. I used a batch size of 2, and trained over about 4 days.
