### ISSUE TITLE
Visualize.py on any images

### ISSUE THREAD

**Issue by giuordy** [yhenon/pytorch-retinanet#137]
Hi. Is there a way to use visualize.py on any images without annotations? @yhenon please

**Comment by hs7251912** [comment]
https://github.com/hs7251912/RetinaNet_pytorch_saplingDetection/blob/master/detect_single_image.py

**Comment by yhenon** [comment]
this has finally been added: https://github.com/yhenon/pytorch-retinanet/blob/master/visualize_single_image.py

**Comment by ajithvallabai** [comment]
@yhenon  where is the csv file in visuvalize_single_image.py, its not in Readme also
