### ISSUE TITLE
Dealing with crowded objects

### ISSUE THREAD

**Issue by antigregory** [yhenon/pytorch-retinanet#14]
Hello Yann,

Firstly, let me thank you for sharing this excellent project!

I have a question regarding the annotations of crowded objects in Ms COCO.
In your code, you [ignore them](https://github.com/yhenon/pytorch-retinanet/blob/6db46e59061bd73fd44900bd8e932df18ba83723/dataloader.py#L86) when loading the data.

If I understand correctly, it means that these annotations are not used as positive targets for the anchors during the training (which is ok), but it also means that the network will be penalized if it detects a (valid) object inside these crowded areas (which is potentially harmful). Am I right? If yes, wouldn't it be more safe to completely ignore images with crowded annotations?

Thank you in advance!

Best,
Grigory

**Comment by yhenon** [comment]
Hi Grigory,

I'm glad you find this repo useful. I had a look at the code, and I'm pretty sure the current implementation does what you suggest it should do.
This line:
```
annotations_ids = self.coco.getAnnIds(imgIds=self.image_ids[image_index], iscrowd=False)
```

Calls the function [here](https://github.com/cocodataset/cocoapi/blob/master/PythonAPI/pycocotools/coco.py#L129), which retrieves a list of image IDs that do not contain an annotation of type `iscrowd`. So those images are indeed entirely ignored.

**Comment by antigregory** [comment]
Thank you very much for your rapid response!
I thought that the coco api function which you mention returns the annotation IDs and not the image ones, but probably you are right... I will check it out in more details!

**Comment by yhenon** [comment]
I'm going to close this for now as I believe everything is in order.
