### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'csv_train'

### ISSUE THREAD

**Issue by Laudarisd** [yhenon/pytorch-retinanet#141]
Hello, I tried to run visualize.py  but I got the following error.
Could you please give me some hint to solve this problem.

`CUDA available: True
Traceback (most recent call last):
  File "visualize.py", line 108, in <module>
    main()
  File "visualize.py", line 41, in main
    dataset_val = CSVDataset(train_file=parser.csv_train, class_list=parser.csv_classes, transform=transforms.Compose([Normalizer(), Resizer()]))
AttributeError: 'Namespace' object has no attribute 'csv_train'
`

Thank you

**Comment by Laudarisd** [comment]
And one more question? 
Why do we need train csv and val annotation csv while doing inference ?
can't we detect the object with model and opencv ?

Thank you

**Comment by nicolas-gervais** [comment]
See pull request #77 it's one minor change

**Comment by Laudarisd** [comment]
Thank you, I already solved the problem.
