### ISSUE TITLE
Transform inconsistent

### ISSUE THREAD

**Issue by jgrietens** [yhenon/pytorch-retinanet#150]
Hi, 

When looking at the tranforms in the dataset implementation I noticed it outputs data of dimensions [width, height, Channel] however, pytorch expects images to be of size [C, W, H]. Is this rectified anywhere before feeding the data to the model ?

**Comment by yhenon** [comment]
this is done https://github.com/yhenon/pytorch-retinanet/blob/master/retinanet/dataloader.py#L335
