### ISSUE TITLE
val error

### ISSUE THREAD

**Issue by wangziyan1234** [yhenon/pytorch-retinanet#153]
Whenever I run to this point, the program breaks~   could  you please help me find the  reason?
![image](https://user-images.githubusercontent.com/48083793/82270013-ffe3e380-99a5-11ea-9df6-0b3e4d748b3b.png)

**Comment by WangKK1996** [comment]
> point
This problem is not caused by this repository. It is beacause your torchvision's version don't match your  python version. You should reinstall your torchvision and try again.

**Comment by wangziyan1234** [comment]
@WangKK1996 thank u so much!
