### ISSUE TITLE
Where to put line for using pretrained model?

### ISSUE THREAD

**Issue by suarezjessie** [yhenon/pytorch-retinanet#154]
Hi, wanted to ask which file specifically and where in the code should I insert this snippet for using the pretrained weights for fine-tuning?

```
retinanet = model.resnet50(num_classes=dataset_train.num_classes(),)
retinanet.load_state_dict(torch.load(PATH_TO_WEIGHTS))
```

**Comment by alisher0717** [comment]
Hi @suarezjessie , how could you solve resuming training from existing model?

**Comment by suarezjessie** [comment]
Oh for this one, I put it within the if-else lines in `train.py` but this is for loading pretrained weights

**Comment by suarezjessie** [comment]
Hi @alisher0717, found the fix for the issue, it's here. Refer to this [issue](https://github.com/yhenon/pytorch-retinanet/issues/157#issue-623142423) that I raised. Thanks!
