### ISSUE TITLE
Multilabel classification and detection

### ISSUE THREAD

**Issue by Sandeep418** [yhenon/pytorch-retinanet#164]
I have multiple labels for a single object,example: image1,x1,y1,x2,y2,label1,label2,..,
this code will work this scenario if it works where I need to modify the code.
Any suggestions?
Thank you.

**Comment by wangziyan1234** [comment]
i think the format should be   image1,x1,y1,x2,y2,label1   image1,x1,y1,x2,y2,label2(csv format)

**Comment by BarCodeReader** [comment]
i dont think this code can work on multi-class after i read through the code...

the classification net use sigmoid as the output layer
also the focal loss uses the formula for binary classifications...

you need to implement your own network

**Comment by Sandeep418** [comment]
> i have exactly the same situation like you.
> 
> here is what i did:
> 
> split the labeling into different files, for your case you need to be
> 
> file 1:
> image1,x1,y1,x2,y2,label1
> 
> file 2:
> image1,x1,y1,x2,y2,label2
> 
> then you train on each different files, then you load the weight one by one and generate your prediction.

Recently I solved this problem I changed the data loader function and Added some extra classification model. i.e. (I want three labels for single bounding box so I created 3 classifiers in the model)
![14_0_0_20170116211955846](https://user-images.githubusercontent.com/40691260/98162626-a47fc080-1f07-11eb-8385-d7634635dcba.jpg)
![21_1_3_20170119155651002](https://user-images.githubusercontent.com/40691260/98162829-ec9ee300-1f07-11eb-93e6-a086d9c0069f.jpg)

**Comment by wangziyan1234** [comment]
@Sandeep418  hello ,  i recently run the multi_labels classification  ,but i don't know how to solve it ,  could you please provide the  code of classifier?  thank you!
