### ISSUE TITLE
Size must be non-negative 

### ISSUE THREAD

**Issue by sim-l3** [yhenon/pytorch-retinanet#17]
pytorch=0.4.1
annot_padded =torch.ones((len(annots),max_num_annots,5))*-1

max_num_annots= negative number?

**Comment by yhenon** [comment]
I've never seen that issue before. Are you using the csv parser? If so, can
you share a sample of your annotations and classes file?

**Comment by minsukim320** [comment]
First, thank you for releasing the code.
I think max_num_annots is problem. 
when annotations does not exist, max_num_annots come to be zero. (in ms coco dataset!)
so, annot_padded = torch.ones((len(annots), 0 , 5)) * (-1)   -> line 330 
thank you

**Comment by sararojas** [comment]
I have the same issue. No matter how much num_workers or batch change.

**Comment by yhenon** [comment]
This should be fixed as of 87c9dcf850f0c0224c5bd5b8f54ca72a001a3072

Thanks for the report.

**Comment by sararojas** [comment]
thanks @yhenon
