### ISSUE TITLE
focal loss

### ISSUE THREAD

**Issue by Hello526** [yhenon/pytorch-retinanet#183]
Hi,
I don't know why the targets are set to -1, which will cause the targets in some positions to always be -1. In focal loss, shouldn't the value of targets be 0 or 1?

https://github.com/yhenon/pytorch-retinanet/blob/ef2c16f4ad66b652b836be36465ee63c978f3194/retinanet/losses.py#L90

@yhenon Looking forward to your reply

**Comment by Hello526** [comment]
For example, in the position of 0.4<IoU<0.5, targets is -1

**Comment by Hello526** [comment]
I'm sorry, I made a mistake

**Comment by RPrudden** [comment]
May I ask what your mistake was, as I have the same confusion
https://github.com/yhenon/pytorch-retinanet/issues/246
