### ISSUE TITLE
`pytorch` version?

### ISSUE THREAD

**Issue by bkj** [yhenon/pytorch-retinanet#21]
Which version of `pytorch` is this intended to be used with?  Thanks!

**Comment by yhenon** [comment]
I've only really tested with 0.4. I'm planning on updating for pytorch 1.0
when possible.

**Comment by dmerrick520** [comment]
The below configurations work for me:

torch==0.4.1
torchvision==0.1.6
python==2.7.6

Doesn't work with 0.4.0 and there are certain configurations of torchvision that won't work with torch==0.4.1

**Comment by Wuziyi616** [comment]
I tried with pytorch 1.0.1 but it didn't work because I can't compile the nms module. Besides, I borrow the nms code from another project and it works fine for me.

**Comment by gunshi** [comment]
@Wuziyi616  which nms implementation did you borrow and could you point me to it? I'm facing a similar issue
Thanks!

**Comment by Wuziyi616** [comment]
@gunshi Hi! I borrow a cpu version of nms from https://github.com/kuangliu/pytorch-retinanet/blob/master/utils.py, starting from line 149.
Also, I've just noticed that the newest release of torchvision has already implemented nms on GPU! Maybe you can also refer to that!
Best wishes!
