### ISSUE TITLE
object has no attribute 'cuda'

### ISSUE THREAD

**Issue by ccl-private** [yhenon/pytorch-retinanet#214]
I download the pre-trained model and run visualize_single_image.py. but I got :
"
File "/home/ccl/Documents/codes/python/pytorch-retinanet/visualize_single_image.py", line 129, in detect_image
    model = model.cuda()
AttributeError: 'collections.OrderedDict' object has no attribute 'cuda'
"

**Comment by qq599127177** [comment]
??
