### ISSUE TITLE
AttributeError: 'OrderedDict' object has no attribute 'cuda' ?

### ISSUE THREAD

**Issue by yghcats** [yhenon/pytorch-retinanet#23]
My torch version is 0.4.1. 
run:  python visualize.py --dataset coco --coco_path ./  --model coco_resnet_50_map_0_335_state_dict.pt
How to solve this problem? AttributeError: 'OrderedDict' object has no attribute 'cuda'

**Comment by yhenon** [comment]
I'm looking into this. Could you please post the full error message? It's almost certainly related to this issue here:  https://discuss.pytorch.org/t/attributeerror-ordereddict-object-has-no-attribute-cuda/3929

**Comment by yghcats** [comment]
@yhenon 
run: python visualize.py --dataset coco --coco_path ./ --model coco_resnet_50_map_0_335_state_dict.pt
error info:
CUDA available: True
loading annotations into memory...
Done (t=0.40s)
creating index...
index created!
Traceback (most recent call last):
  File "visualize.py", line 97, in <module>
    main()
  File "visualize.py", line 51, in main
    retinanet = retinanet.cuda()
AttributeError: 'OrderedDict' object has no attribute 'cuda'

thanks!

**Comment by yhenon** [comment]
This was a bit of an oversight on my part. There are 2 versions of the model available, one saved as a state dict and one saved directly using `torch.save()`. You'll need the one saved using `torch.save()` to use with visualize.py

I've updated the readme to clarify this (https://github.com/yhenon/pytorch-retinanet#pre-trained-model)

The model is available here: https://drive.google.com/open?id=1hCtM35R_t6T8RJVSd74K4gB-A1MR-TxC

**Comment by haqkiemdaim** [comment]
> @yhenon
> run: python visualize.py --dataset coco --coco_path ./ --model coco_resnet_50_map_0_335_state_dict.pt
> error info:
> CUDA available: True
> loading annotations into memory...
> Done (t=0.40s)
> creating index...
> index created!
> Traceback (most recent call last):
> File "visualize.py", line 97, in 
> main()
> File "visualize.py", line 51, in main
> retinanet = retinanet.cuda()
> AttributeError: 'OrderedDict' object has no attribute 'cuda'
> 
> thanks!

@yghcats hi there. just want to ask how did you solve this ya ?

**Comment by FHDD** [comment]
I solve it in this way:

in visulize.py

1. the model I use is: model_path='./coco_resnet_50_map_0_335_state_dict.pt'
2. change the origin code "retinanet = torch.load(parser.model, encoding='latin1')" into :
	retinanet = model.resnet50(num_classes=dataset_val.num_classes(),)
	retinanet.load_state_dict(torch.load(parser.model))

then, done.
<img width="580" alt="git" src="https://user-images.githubusercontent.com/39789261/115673749-8b68b000-a37f-11eb-90e2-a1c58e641642.png">

**Comment by Meoooww** [comment]
> * coco_resnet_50_map_0_335_state_dict.pt'
> * change the origin code "retinanet = torch.load(parser.model, encoding='latin1')" into :
>   retinanet = model.resnet50(num_classes=dataset_val.num_classes(),)
>   retinanet.load_state_dict(torch.load(p
so how to intialize 'model'?

**Comment by Meoooww** [comment]
> I solve it in this way:
> 
> in visulize.py
> 
> 1. the model I use is: model_path='./coco_resnet_50_map_0_335_state_dict.pt'
> 2. change the origin code "retinanet = torch.load(parser.model, encoding='latin1')" into :
>    retinanet = model.resnet50(num_classes=dataset_val.num_classes(),)
>    retinanet.load_state_dict(torch.load(parser.model))
> 
> then, done. <img alt="git" width="580" src="https://user-images.githubusercontent.com/39789261/115673749-8b68b000-a37f-11eb-90e2-a1c58e641642.png">

**so how to intialize 'model'?**

**Comment by Meoooww** [comment]
> so how to intialize 'model'?

so how to intialize 'model'?

> This was a bit of an oversight on my part. There are 2 versions of the model available, one saved as a state dict and one saved directly using `torch.save()`. You'll need the one saved using `torch.save()` to use with visualize.py
> 
> I've updated the readme to clarify this (https://github.com/yhenon/pytorch-retinanet#pre-trained-model)
> 
> The model is available here: https://drive.google.com/open?id=1hCtM35R_t6T8RJVSd74K4gB-A1MR-TxC

**so how to intialize 'model'?**
