### ISSUE TITLE
IndexError: index -1 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by nikeshdevkota** [yhenon/pytorch-retinanet#254]
I followed the instructions to train the model using CSV files but I keep getting  IndexError: index -1 is out of bounds for axis 0 with size 0 in line 240 of csv_eval. When I printed the true positives and false positives, they were empty arrays. I can't figure out the problem as I used https://github.com/martinzlocha/anchor-optimization to optimize the anchor configuration for my dataset.

I am running the code on the Tsinghua-Tencent 100k traffic sign benchmark. I augmented the data before sending it to the model because I needed class-wise augmentation to generate enough training images.  Right now, I have around 800-1800 images per class and I have 33 classes.

**Comment by nikeshdevkota** [comment]
The error was due to the true positives and false positives lists being empty which was caused by not optimizing the anchor configuration.

**Comment by Dickoabc123** [comment]
hey @nikeshdevkota how did you resolve this issue please?
I get this error:
csv_eval.py", line 240, in evaluate
    print("Precision: ",precision[-1])
IndexError: index -1 is out of bounds for axis 0 with size 0

**Comment by lexical-yoda** [comment]
Could you please explain more about it? 
I'm having the same error.
