### ISSUE TITLE
the anchors coordinate transform

### ISSUE THREAD

**Issue by designerZhou** [yhenon/pytorch-retinanet#28]
in file "anchors.py",at line:66-68
the calculate is right?    
# transform from (x_ctr, y_ctr, w, h) -> (x1, y1, x2, y2)
    anchors[:, 0::2] -= np.tile(anchors[:, 2] * 0.5, (2, 1)).T
    anchors[:, 1::2] -= np.tile(anchors[:, 3] * 0.5, (2, 1)).T
in my opinion ,it should be : 
# transform from (x_ctr, y_ctr, w, h) -> (x1, y1, x2, y2)
    anchors[:, 0::2] -= np.tile(anchors[:, 2] * 0.5, (2, 1)).T
    anchors[:, 1::3] -= np.tile(anchors[:, 3] * 0.5, (2, 1)).T
is it right?

**Comment by yhenon** [comment]
The current implementation is correct. This `anchors[:, 1::3]` would use a stride of 3, which is not what we want.
