### ISSUE TITLE
AspectRatioBasedSampler has no defined sampler

### ISSUE THREAD

**Issue by TheShadow29** [yhenon/pytorch-retinanet#29]
The `train_dataloader` uses `AspectRatioBasedSampler` as its batch_sampler. The len of AspectRatioSampler requires `self.sampler`https://github.com/yhenon/pytorch-retinanet/blob/master/dataloader.py#L448

However self.sampler is not defined anywhere. 

Edit: I think it should `len(self.datasource)` instead of `len(self.sampler)`. Please correct me if I am wrong.

**Comment by yhenon-nextdroid** [comment]
I believe you are indeed correct (although it is `data_source` not `datasource`). Thanks!

**Comment by yhenon** [comment]
I believe you are indeed correct, although it is `data_source` not `datasource`. Thanks!

Fixed in 1135e18b835481b18fd0d4e1613c87afc2bc7d46
