### ISSUE TITLE
How to train again on the basis of the last training

### ISSUE THREAD

**Issue by clw5180** [yhenon/pytorch-retinanet#58]
If I have trained for 100 epoches and I still wanted to continue training on the basis of epoch 100's model, can I just use the code as pretrained model below:
```
retinanet = model.resnet50(num_classes=dataset_train.num_classes(),)
retinanet.load_state_dict(torch.load(PATH_TO_SAVED_WEIGHTS_OF_100_EPOCH))
```

**Comment by suarezjessie** [comment]
Hi @clw5180, did this work for you?

**Comment by skimaza** [comment]
@suarezjessie 
seems to work for me with the code below.
retinanet = torch.load(PATH_TO_SAVED_WEIGHTS_OF_100_EPOCH)
