### ISSUE TITLE
ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead

### ISSUE THREAD

**Issue by wwfnwg** [yhenon/pytorch-retinanet#66]

**Comment by kyle0x54** [comment]
You can solve the problem by degrading pytorch to 0.4.x

**Comment by huaifeng1993** [comment]
I meet the same error when using pytorch1.0 .but I solved that with  replace the nms lib with the code from https://github.com/huaifeng1993/NMS which nms implemented by cython。

**Comment by CS-Jackson** [comment]
Hi, @huaifeng1993 . Can you share more detail about the NMS, do you build again after replacing the nms lib?

**Comment by liangzz1991** [comment]
> I meet the same error when using pytorch1.0 .but I solved that with replace the nms lib with the code from https://github.com/huaifeng1993/NMS which nms implemented by cython。

i solved it .you can used this link to replace the original nms. this code has been compiled.if you need compile:
1.cd nms ,rm -rf /build,rm *.so
2.cd ..，python setup3.py build_ext --inplace
at last,you need modify code in model.py:
#from lib.nms.pth_nms import pth_nms
from lib.nms.gpu_nms import gpu_nms
and
# return pth_nms(dets, thresh)
 return gpu_nms(dets, thresh)

**Comment by liangzz1991** [comment]
> I meet the same error when using pytorch1.0 .but I solved that with replace the nms lib with the code from https://github.com/huaifeng1993/NMS which nms implemented by cython。

i solved it .you can used this link to replace the original nms. this code has been compiled.if you need compile:
1.cd nms ,rm -rf /build,rm *.so
2.cd ..，python setup3.py build_ext --inplace
at last,you need modify code in model.py:
#from lib.nms.pth_nms import pth_nms
from lib.nms.gpu_nms import gpu_nms
and
# return pth_nms(dets, thresh)
return gpu_nms(dets, thresh)

**Comment by liangzz1991** [comment]
> I meet the same error when using pytorch1.0 .but I solved that with replace the nms lib with the code from https://github.com/huaifeng1993/NMS which nms implemented by cython。

i solved it .you can used this link to replace the original nms. this code has been compiled.if you need compile:
1.cd nms ,rm -rf /build,rm *.so
2.cd ..，python setup3.py build_ext --inplace
at last,you need modify code in model.py:
#from lib.nms.pth_nms import pth_nms
from lib.nms.gpu_nms import gpu_nms
and

#return pth_nms(dets, thresh)
return gpu_nms(dets, thresh)

**Comment by Scienceseb** [comment]
That dont work for me where do you put gpu_nms is it the .pyx file ? What modification I have to do ? Nothing is working for me lol Do I need to do your step 1 and 2 ?

**Comment by Scienceseb** [comment]
That dont work for me where do you put gpu_nms is it the .pyx file ? What modification I have to do ? Nothing is working for me lol Do I need to do your step 1 and 2 ?

**Comment by WeiYunShu94** [comment]
> > I meet the same error when using pytorch1.0 .but I solved that with replace the nms lib with the code from https://github.com/huaifeng1993/NMS which nms implemented by cython。
> 
> i solved it .you can used this link to replace the original nms. this code has been compiled.if you need compile:
> 1.cd nms ,rm -rf /build,rm *.so
> 2.cd ..，python setup3.py build_ext --inplace
> at last,you need modify code in model.py:
> #from lib.nms.pth_nms import pth_nms
> from lib.nms.gpu_nms import gpu_nms
> and
> 
> #return pth_nms(dets, thresh)
> return gpu_nms(dets, thresh)

> I meet the same error when using pytorch1.0 .but I solved that with replace the nms lib with the code from https://github.com/huaifeng1993/NMS which nms implemented by cython。

I run `python set3up.py build`, unfortunate, meet a error:
running build
running build_ext
skipping 'nms/gpu_nms.cpp' Cython extension (up-to-date)
building 'nms.gpu_nms' extension
creating build
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/nms
/usr/local/cuda-9.0/bin/nvcc -I/home/atr/WMJ/environment_mianjin/maskrcnn_benchmark/lib/python3.6/site-packages/numpy/core/include -I/usr/local/cuda-9.0/include -I/usr/include/python3.6m -I/home/atr/WMJ/environment_mianjin/maskrcnn_benchmark/include/python3.6m -c nms/nms_kernel.cu -o build/temp.linux-x86_64-3.6/nms/nms_kernel.o -arch=sm_35 --ptxas-options=-v -c --compiler-options '-fPIC'
ptxas info    : 0 bytes gmem
ptxas info    : Compiling entry function '_Z10nms_kernelifPKfPy' for 'sm_35'
ptxas info    : Function properties for _Z10nms_kernelifPKfPy
    0 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 22 registers, 1280 bytes smem, 344 bytes cmem[0], 12 bytes cmem[2]
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/atr/WMJ/environment_mianjin/maskrcnn_benchmark/lib/python3.6/site-packages/numpy/core/include -I/usr/local/cuda-9.0/include -I/usr/include/python3.6m -I/home/atr/WMJ/environment_mianjin/maskrcnn_benchmark/include/python3.6m -c nms/gpu_nms.cpp -o build/temp.linux-x86_64-3.6/nms/gpu_nms.o -Wno-unused-function
nms/gpu_nms.cpp:4:10: fatal error: Python.h: No such file or directory
 #include "Python.h"
          ^~~~~~~~~~
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
What happened to this?

**Comment by liangzz1991** [comment]
> #include "Python.h"
> ^~~~~~~~~~
> compilation terminated.
> error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

no 'Python.h',,,,,,, is used by gcc to build cpp. You need to install a package :
sudo apt-get install python-dev

**Comment by feixiangdekaka** [comment]
> > I meet the same error when using pytorch1.0 .but I solved that with replace the nms lib with the code from https://github.com/huaifeng1993/NMS which nms implemented by cython。
> 
> i solved it .you can used this link to replace the original nms. this code has been compiled.if you need compile:
> 1.cd nms ,rm -rf /build,rm *.so
> 2.cd ..，python setup3.py build_ext --inplace
> at last,you need modify code in model.py:
> #from lib.nms.pth_nms import pth_nms
> from lib.nms.gpu_nms import gpu_nms
> and
> 
> #return pth_nms(dets, thresh)
> return gpu_nms(dets, thresh)

raise error:
TypeError: Argument 'dets' has incorrect type (expected numpy.ndarray, got Tensor)
need change dets to numpy  in   nms  function, then  change  anchors_nms_idx  to  torch.int64  in  model.py .

**Comment by liangzz1991** [comment]
you need change the dets to numpy:
add in gpu_nms() :
dets = dets.numpy()

**Comment by Peter-Strain** [comment]
Got the error as above 'TypeError: Argument 'dets' has incorrect type (expected numpy.ndarray, got Tensor)' 

Added;
def nms(dets, thresh):
    "Dispatch to either CPU or GPU NMS implementations.\
    Accept dets as tensor"""
    #return pth_nms(dets, thresh)
    dets = dets.numpy()
    return gpu_nms(dets, thresh)     

Now I am getting the error;

TypeError: can't convert CUDA tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first. 

Does anyone know a fix?

**Comment by nassarofficial** [comment]
> you need change the dets to numpy:
> add in gpu_nms() :
> dets = dets.numpy()

where is gpu_nms() ? Is it gpu_nms.pyx ?

**Comment by nassarofficial** [comment]
> you need change the dets to numpy:
> add in gpu_nms() :
> dets = dets.numpy()

Where is gpu_nms()? is it in gpu_nms.pyx, because I added the line, and I am still getting :

TypeError: Argument 'dets' has incorrect type (expected numpy.ndarray, got Tensor)

**Comment by liangzz1991** [comment]
> > you need change the dets to numpy:
> > add in gpu_nms() :
> > dets = dets.numpy()
> 
> Where is gpu_nms()? is it in gpu_nms.pyx, because I added the line, and I am still getting :
> 
> TypeError: Argument 'dets' has incorrect type (expected numpy.ndarray, got Tensor)

In front of “gpu_nms()” in model.py:
def nms(dets, thresh):
      dets = dets.numpy()
      return gpu_nms(dets, thresh)

**Comment by Wuziyi616** [comment]
> 
> 
> I meet the same error when using pytorch1.0 .but I solved that with replace the nms lib with the code from https://github.com/huaifeng1993/NMS which nms implemented by cython。

Hi, can you share your result using this nms code? After I replace the original nms code with this new one, I only got an map=0.3 on coco dataset. I wonder if it's because of the nms code.

**Comment by Wuziyi616** [comment]
@liangzz1991 Hi, can you share your training result using the nms code you mentioned? After I replace the original nms code with this new one, I only got an map=30% on coco dataset. I wonder if it's because of the nms code.

**Comment by sindhurk** [comment]
> > I meet the same error when using pytorch1.0 .but I solved that with replace the nms lib with the code from https://github.com/huaifeng1993/NMS which nms implemented by cython。
> 
> i solved it .you can used this link to replace the original nms. this code has been compiled.if you need compile:
> 1.cd nms ,rm -rf /build,rm *.so
> 2.cd ..，python setup3.py build_ext --inplace
> at last,you need modify code in model.py:
> #from lib.nms.pth_nms import pth_nms
> from lib.nms.gpu_nms import gpu_nms
> and
> 
> #return pth_nms(dets, thresh)
> return gpu_nms(dets, thresh)

After following these steps to build, I get:
```
running build_ext
skipping 'nms/gpu_nms.cpp' Cython extension (up-to-date)
```
followed by this error while for training:
 `ImportError: libcudart.so.8.0: cannot open shared object file: No such file or directory`

**Comment by CerrieJ** [comment]
> > > you need change the dets to numpy:
> > > add in gpu_nms() :
> > > dets = dets.numpy()
> > 
> > 
> > Where is gpu_nms()? is it in gpu_nms.pyx, because I added the line, and I am still getting :
> > TypeError: Argument 'dets' has incorrect type (expected numpy.ndarray, got Tensor)
> 
> In front of “gpu_nms()” in model.py:
> def nms(dets, thresh):
> dets = dets.numpy()
> return gpu_nms(dets, thresh)

`  File "/home//workSpace/pytorch-retinanet/model.py", line 14, in nms
    dets = dets.numpy()
TypeError: can't convert CUDA tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.`

then edit to :
`dets = tets.cpu().numpy()`
then: 
` File "/home/anaconda2/lib/python2.7/site-packages/torch/tensor.py", line 412, in __array__
    return self.numpy()
TypeError: can't convert CUDA tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.`

**Comment by liangzz1991** [comment]
@Wuziyi616 I can not use this nms to train the model, only replaced the original nms in the inference used author‘s model , the result is ok. ..But I don't think this nms will have a big impact on your MAP, if the source train code is perfect.

**Comment by Wuziyi616** [comment]
@liangzz1991 Thanks for your reply! I've solved it by turning to another NMS implementation but thank you anyway!

**Comment by SchroeterJulien** [comment]
@Wuziyi616 Would you have a link to the NMS implementation you used? Which maP did you obtain? Thank you in advance

**Comment by lushishuai** [comment]
> > 使用pytorch1.0时遇到相同的错误，但是我用https://github.com/huaifeng1993/NMS中的代码替换了nms lib，该错误由cython实现。
> 
> 我解决了。您可以使用此链接替换原始nms。此代码已编译。如果需要编译：
> 1.cd nms，rm -rf / build，rm * .so
> 2.cd ..，python setup3.py build_ext-
> 最后，需要在模型中修改代码。 py：
> #from lib.nms.pth_nms
> 从lib.nms.gpu_nms导入pth_nms import gpu_nms
> 和
> 
> #return pth_nms（dets，thresh）
> 返回gpu_nms（dets，thresh）


could you tell me where the model.py is?

**Comment by Scienceseb** [comment]
> @liangzz1991 Thanks for your reply! I've solved it by turning to another NMS implementation but thank you anyway!

What implementation did you used ?

**Comment by Hersue** [comment]
> > > you need change the dets to numpy:
> > > add in gpu_nms() :
> > > dets = dets.numpy()
> > 
> > 
> > Where is gpu_nms()? is it in gpu_nms.pyx, because I added the line, and I am still getting :
> > TypeError: Argument 'dets' has incorrect type (expected numpy.ndarray, got Tensor)
> 
> In front of “gpu_nms()” in model.py:
> def nms(dets, thresh):
> dets = dets.numpy()
> return gpu_nms(dets, thresh)

Solved. In addition, the "sm architecture" in setup3.py also need to be modified according to your machine. For me, 2080 Ti should be SM75.

**Comment by Note-Liu** [comment]
> you need change the dets to numpy:
> add in gpu_nms() :
> dets = dets.numpy()
> 
> Where is gpu_nms()? is it in gpu_nms.pyx, because I added the line, and I am still getting :
> TypeError: Argument 'dets' has incorrect type (expected numpy.ndarray, got Tensor)
> 
> In front of “gpu_nms()” in model.py:
> def nms(dets, thresh):
> dets = dets.numpy()
> return gpu_nms(dets, thresh)
> 
> Solved. In addition, the "sm architecture" in setup3.py also need to be modified according to your machine. For me, 2080 Ti should be SM75.

how to determine sm?
I use 1070Ti

**Comment by ta946** [comment]
> > you need change the dets to numpy:
> > add in gpu_nms() :
> > dets = dets.numpy()
> > Where is gpu_nms()? is it in gpu_nms.pyx, because I added the line, and I am still getting :
> > TypeError: Argument 'dets' has incorrect type (expected numpy.ndarray, got Tensor)
> > In front of “gpu_nms()” in model.py:
> > def nms(dets, thresh):
> > dets = dets.numpy()
> > return gpu_nms(dets, thresh)
> > Solved. In addition, the "sm architecture" in setup3.py also need to be modified according to your machine. For me, 2080 Ti should be SM75.
> 
> how to determine sm?
> I use 1070Ti

https://developer.nvidia.com/cuda-gpus
under "CUDA-Enabled GeForce and TITAN Products"
GeForce GTX 1070 | 6.1
so yours will be:
sm61

**Comment by Note-Liu** [comment]
> you need change the dets to numpy:
> add in gpu_nms() :
> dets = dets.numpy()
> Where is gpu_nms()? is it in gpu_nms.pyx, because I added the line, and I am still getting :
> TypeError: Argument 'dets' has incorrect type (expected numpy.ndarray, got Tensor)
> In front of “gpu_nms()” in model.py:
> def nms(dets, thresh):
> dets = dets.numpy()
> return gpu_nms(dets, thresh)
> Solved. In addition, the "sm architecture" in setup3.py also need to be modified according to your machine. For me, 2080 Ti should be SM75.
> 
> how to determine sm?
> I use 1070Ti
> 
> https://developer.nvidia.com/cuda-gpus
> under "CUDA-Enabled GeForce and TITAN Products"
> GeForce GTX 1070 | 6.1
> so yours will be:
> sm61

Thank you for your answer!

**Comment by yhenon** [comment]
I've updated this repo to support pytorch 1.0. This should no longer be an issue, as torchvision now has an nms layer

**Comment by 1165628028** [comment]
> > I meet the same error when using pytorch1.0 .but I solved that with replace the nms lib with the code from https://github.com/huaifeng1993/NMS which nms implemented by cython。
> 
> i solved it .you can used this link to replace the original nms. this code has been compiled.if you need compile:
> 1.cd nms ,rm -rf /build,rm *.so
> 2.cd ..，python setup3.py build_ext --inplace
> at last,you need modify code in model.py:
> #from lib.nms.pth_nms import pth_nms
> from lib.nms.gpu_nms import gpu_nms
> and
> 
> #return pth_nms(dets, thresh)
> return gpu_nms(dets, thresh)

when i run python setup3.py build ,it report:

ModuleNotFoundError: No module named 'Cython'

how to resolve it?
