### ISSUE TITLE
undefined symbol : PyInt_FromLong

### ISSUE THREAD

**Issue by DecentMakeover** [yhenon/pytorch-retinanet#7]
Hi thanks for your code!

Im getting this error when i try to run on my custom data

    Traceback (most recent call last):
      File "train.py", line 19, in <module>
        import model
      File "/media/sdc/Ryan/pytorch-retinanet/model.py", line 9, in <module>
        from lib.nms.pth_nms import pth_nms
      File "/media/sdc/Ryan/pytorch-retinanet/lib/nms/pth_nms.py", line 2, in <module>
        from ._ext import nms
      File "/media/sdc/Ryan/pytorch-retinanet/lib/nms/_ext/nms/__init__.py", line 3, in <module>
        from ._nms import lib as _lib, ffi as _ffi
    ImportError: /media/sdc/Ryan/pytorch-retinanet/lib/nms/_ext/nms/_nms.so: undefined symbol:PyInt_FromLong`

anything obvious i'm missing?

**Comment by yhenon** [comment]
Hi,
I hope you find this repo useful!

Did you compile the nms extension as indicated in step 4 of installation in
the Readme?

**Comment by DecentMakeover** [comment]
Sorry for the late reply ,
I did,
I did not have a make.sh file, so i ran build.sh , I got a few warnings though

**Comment by yhenon** [comment]
I'm not 100% sure what's going on. It would help me out if you could post:

- the command you are using to launch

- the compiler warnings from building the extension

- your version of cuda, pytorch and python

Thanks!

**Comment by DecentMakeover** [comment]
Sure, Give me a minute

**Comment by DecentMakeover** [comment]
Not sure where to reach you, so posting this here ,
Hi ,I had just another question ,Most of the datasets have integer values as their bounding box co-ordinates like `56 43 22 77` etc, but for the open dataset challenge the bounding box co-ordinates are in float values like `0.0012, 0.4120, 0.1250, 0.2224` etc, so when training my classification loss decreases but my regression loss stays 0, Any suggestion on what i could modify to make this work.For now in the dataloader script from line 274-277 i have changed the int argument to float to make it to accept float values.Thanks in advance

**Comment by yhenon** [comment]
Hi,

Please go ahead and create a separate issue for this, it keep things more
organized and makes it easier for people to search (I get notified of any
issues, so there's no trouble contacting me).

Did you solve the original problem?

**Comment by DecentMakeover** [comment]
Sure, 

Yes ,The original issue was solved

**Comment by Vikramsinh** [comment]
I have install pysftp library using **yum install pysftp -t** . on AMI linux command prompt and make zip file of it and upload it to AWS lambda layer. but still I am getting

> Undefined Symbol: PyInt_FromLong

**Please help**
