### ISSUE TITLE
TypeError: dist must be a Distribution instance after bash build.sh

### ISSUE THREAD

**Issue by allenyh** [yhenon/pytorch-retinanet#76]
Has anyone encounter the same problem? and how do you solve that?
Google said it's caused by version of setuptools and distutils mismatching.
But I still encounter this problem after upgrading both setuptools and distutils to the latest version

**Comment by PingHGao** [comment]
I have encounter the same error，and I did not find package 'distutils' through 'pip search' or 'pip install distutils'。I wander whether the ‘distutils’ is a python package.

**Comment by PingHGao** [comment]
Did you solve this problem? @allenyh

**Comment by allenyh** [comment]
> Did you solve this problem? @allenyh

No...still not found any solution for this.
BTW, I have also tried with every other python version I have installed in my PC, in python2.7, 3.5 and 3.6
,and all encounter the same problem.

**Comment by PingHGao** [comment]
> > Did you solve this problem? @allenyh
> 
> No...still not found any solution for this.
> BTW, I have also tried with every other python version I have installed in my PC, in python2.7, 3.5 and 3.6
> ,and all encounter the same problem.

I am using Python3.6 and pytorch1.1. I made some change in build.py. I thought this may be the cause. After talking with you，I  think I maybe wrong

**Comment by allenyh** [comment]
> > > Did you solve this problem? @allenyh
> > 
> > 
> > No...still not found any solution for this.
> > BTW, I have also tried with every other python version I have installed in my PC, in python2.7, 3.5 and 3.6
> > ,and all encounter the same problem.
> 
> I am using Python3.6 and pytorch1.1. I made some change in build.py. I thought this may be the cause. After talking with you，I think I maybe wrong

What change have you made in build.py? is it about the buildextension?

**Comment by PingHGao** [comment]
I have solved this problem by changing my pytorch vision from 1.1 to 0.4. Hope this information can do some help. @allenyh

**Comment by allenyh** [comment]
> I have solved this problem by changing my pytorch vision from 1.1 to 0.4. Hope this information can do some help. @allenyh

Yep, I've also solved this by downgrade pytorch from 1.0 to 0.4, but now I encounter another problem lol

**Comment by PingHGao** [comment]
> > I have solved this problem by changing my pytorch vision from 1.1 to 0.4. Hope this information can do some help. @allenyh
> 
> Yep, I've also solved this by downgrade pytorch from 1.0 to 0.4, but now I encounter another problem lol

haha. wish  you good luck
