### ISSUE TITLE
How did you save model state dict ?

### ISSUE THREAD

**Issue by jimeffry** [yhenon/pytorch-retinanet#92]
In training  I save the mdoel using torch.save(retinanet.state_dict()). While  using retinanet.load_state_dict(torch.load(load_path)), it failed. Could you share your save model state dict codes? Thank you!

**Comment by xiaoxifei1223** [comment]
if you want to load model state dict，you could change the save step as “torch.save(retinanet.module.state_dict(), './result/{}_retinanet_{}.pt'.format(parser.dataset, epoch_num))”, and if you want to load model from the default code, you should load like this "retinanet = torch.load(model_path)"

**Comment by jimeffry** [comment]
Thank you very much
